### ISSUE TITLE
Number of Metatype Relationship Pairs limited to 1000

### ISSUE THREAD

**Issue by brennanxyz** [idaholab/Deep-Lynx#102]
## Bug Description
It seems that the number of Metatype Relationship Pairs is limited to 1000
![rels](https://user-images.githubusercontent.com/53807547/105738816-af3d6680-5ef4-11eb-9e0b-4ad11b7234c0.PNG)

## Steps to Reproduce
Import a container with the DIAMOND ontology. See number of relationship pairs is 1000. Attempt to add an additional relationship pair, then search in the list

## Impact
Requires reduction of the full ontology

**Comment by DnOberon** [comment]
@brennanxyz - this isn't actually an issue of adding more than 1000 to the relationship pairs. The return is capped at 1000 records if the API call is made without a limit/offset parameter. In order to solve this Jeren's issue #89 Modify Taxonomy Tables to be Data Tables needs to be implemented. This will fix the return capping at 1000 records.
